version: 2
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image
          command: |
            docker build -t "$DOCKER_REPO:$CIRCLE_BUILD_NUM" .
      - deploy:
          name: upload to dockerhub
          command: |
            if [[ -n "$DOCKER_USER" ]]; then
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
              docker push "$DOCKER_REPO:$CIRCLE_BUILD_NUM"
            fi
workflows:
  build:
    jobs:
      - build